# docker-compose.yml
version: '3'

services:

  proxy:
    container_name: proxy-c
    restart: always
    depends_on:
      - gitlab
    hostname: proxy
    image: nginx
    ports:
      - 80:80     # gitlab http
      - 443:443   # gitlab https
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./key.0419:/etc/ssl/private

  gitlab:
    image: 'gitlab/gitlab-ce:13.12.5-ce.0'
    restart: always
    hostname: 'gitlab'
    container_name: gitlab-c
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.kvisiondev.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      #- '80:80'
      #- '443:443'
      - '1022:22'
    volumes:
      - '/mnt/gitlab/config:/etc/gitlab'
      - '/mnt/gitlab/logs:/var/log/gitlab'
      - '/mnt/gitlab/data:/var/opt/gitlab'
      - '/mnt/gitlab/backups:/var/opt/gitlab/backups'
